project:
  type: website
editor:
  render-on-save: true
knitr: true
#Website
website:
  ## Turn Breadcrumbs off
  bread-crumbs: false
  ## Icon seen on tab
  favicon: /images/quarto_quarters.png
  ## Previous and next page links at bottom
  page-navigation: true
  title: "MG Quarto Guide"
  description: "A guide to using quarto"
##Navbar
  navbar:
    title: MG Quarto Guide
    logo: "images/quarto_quarters.png"
    # When to collapse to hamburger menu
    # lg is default
    collapse-below: lg
###Navbar left
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Setup"
        href: setup/setup.qmd
      - text: "qmd"
        href: qmds/qmds.qmd
      - text: "css"
        href: css/css.qmd
      - text: "yml"
        href: yml/yml.qmd
###Navbar right
    right:
    # List of icons: https://icons.getbootstrap.com/
      - icon: cup
        href: https://ko-fi.com/waveofinspiration
        aria-label: Ko-fi
      - icon: bluesky
        href: https://bsky.app/profile/m-gemmell.bsky.social
        aria-label: BlueSky
      - icon: github
        href: https://github.com/m-gemmell/Quarto_guide
        aria-label: GitHub
##Page footer
  page-footer:
    left: |
      ![](/images/quarto_quarters.png){width=50}
    center: |
      [![](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/K3K6IRLA0)
##Sidebar
  sidebar:
    - id: Overview
      title: "Overview"
      style: "floating"
      contents:
        - href: index.qmd
    - id: Setup
      title: "Setup"
      style: "floating"
      collapse-level: 2
      contents:
      - href: setup/setup.qmd
    - id: qmd
      title: "qmd"
      style: "floating"
      collapse-level: 2
      contents:
      - href: qmds/qmds.qmd
      - section: "Static"
        contents:
        - href: qmds/markdown.qmd
        - href: qmds/images.qmd
        - href: qmds/callouts.qmd
        - href: qmds/icons.qmd
        - href: qmds/tables.qmd
        - href: qmds/github_code_embed.qmd
      - section: "Interactive"
        contents:
        - href: qmds/code.qmd
        - href: qmds/tippy_tooltips.qmd
        - href: qmds/webexercises.qmd
        - href: qmds/videos.qmd
    - id: css
      title: "css"
      style: "floating"
      collapse-level: 2
      contents:
      - href: css/css.qmd
      - section: "Dark and Light"
        contents:
        - href: css/dark_scss.qmd
        - href: css/light_scss.qmd
    - id: yml
      title: "yml"
      style: "floating"
      collapse-level: 2
      contents:
      - href: yml/yml.qmd
      - href: yml/yml_file.qmd
      - href: yml/project_n_misc.qmd
      - section: "Website & structure"
        contents:
        - href: yml/website.qmd
        - href: yml/navbar.qmd
        - href: yml/page_footer.qmd
        - href: yml/sidebar.qmd
      - href: yml/format.qmd
#Format
format:
  html:
###Include table of contents
### "On this page" right of page
    toc: true

###Page size
    grid:
####Width of sidebar
      sidebar-width: 200px
####Max width of main page
      body-width: 1200px
####Width of empty margin at right of toc
#### needed to give room for long headers
      margin-width: 150px
####Space separating body from sidebar and toc  
      gutter-width: 10px

###Code highlighting style
### a11y is accessible and auto switches between dark and light mode
    highlight-style: a11y

####Code will overflow in code blocks
####set to scroll for scroll (i.e. horizontal scroll at bottom of block)
    code-overflow: wrap

###Themes
###HTML themes: https://quarto.org/docs/output-formats/html-themes.html
    theme:
####Dark theme with scss file
      dark: [darkly, styles_dark.scss]
####Light theme with scss
      light: [styles_light.scss]
####Any text not determined in scss files will be mainfont
    mainfont: Lexend

###Paths for webexercises files
    css: include/webex.css
    include-after-body: include/webex.js