# Setup

To use quarto I would suggest using [VScode](https://code.visualstudio.com/) (You can "Disable Ai Features" in the settings).

To install Quarto see [The Quarto Get Started page](https://quarto.org/docs/get-started/).

## Extensions

For this site you will also want to follow the below install instruction.

### R

[R in Visual Studio Code](https://code.visualstudio.com/docs/languages/r)

### Spell checker

[Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker): Useful for spell checking normal words

When using this click on a misspelt word (signified by squiggly underlining) and press "ctrl+." to get a dropdown of suggestions

To change to GB spelling:

1. Go to "Extension" on VScode (On far left, icon is three squares and a diamond)
2. Click on the gear icon for Code Spell Checker
3. Click on "Settings"
4. Change "C Spell: Language" to "en-GB"

## Create Quarto website project

You can create a quarto project in 2 different way, a quarto command or copying a template.

### Quarto command

In the command palette in VScode (the text bar at the top middle) type in the following:

`>Quarto: Create Project`

Further instructions are here: [Quarto Website Quick Start](https://quarto.org/docs/websites/#quick-start)

### Copying a template

Optionally, you can copy a template or other project from github and edit it.

If you already have the files you can then copy and paste to a new directory (ensure you don't copy over any git files/directories if you do this).

To download all the files of a gihub repo:

1. Navigate to the page via a browser (e.g. https://github.com/m-gemmell/Quarto_guide)
2. Click on the green `<> Code` button
3. Select "Download ZIP"